// Replace only the `competition` object in site/data-provider.ts.
competition: {
  mode: "untimed",
  metricField: "bestScore",
  previousPeriodMetricField: "previousDayBestScore",
  metricLabel: "SCORE",
  metricSingular: "point",
  metricPlural: "points",
  previousPeriodLabel: "yesterday",
  previousPodiumPlaceholder: "Yesterday's podium · no score yet",
  activity: {
    resultType: "live",
    streakType: "streak",
    rankingType: "arena",
    resultBadge: "SCORE",
    streakBadge: "STREAK",
    rankingBadge: "RANK",
    waitingText: "Waiting for the next completed word run…",
    resultVerb: "scored",
    defaultOpponent: "a new score",
    defaultModeLabel: "Text Twist 2 Untimed",
    streakNoun: "round streak",
    streakFallbackLabel: "Word Streak",
    rankingFallbackLabel: "Word Master",
    revengeAchievementKey: "",
    revengeText: "",
  },
},

