import type { GameDefinitionData } from "@/config/game-schema";
import { gameAssetUrl } from "@/site/site";

export const GAME_DEFINITIONS = {
  "2v2-io": {
    categoryId: "sci-fi-clicker-games",
    title: "2v2.io",
    image: "/2v2-io-logo.webp",
    plays: 0,
    tags: ["PvP", "Building", "Battle Royale"],
    gameAttributes: {
      playerModes: ["two-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: "https://game.1v1-lol.cc/1v1-lol-games/2v2-io/2v2-io.html",
      coverImage: "/2v2-io-bj.webp",
      coverAlt: "2v2.io Background",
      metadataDescription: "2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​",
      description: "<section><h3>About 2v2.io</h3><p>2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​</p></section>",
    },
  },
  "planet-clicker": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker",
    image: "/planet-clicker-logo.webp",
    plays: 0,
    tags: ["Building"],
    gameAttributes: {
      playerModes: ["single-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["building"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Planet Clicker is an addictive idle game where you explore planets, upgrade your space fleet, and build your galactic empire. Click your way to success and become the ultimate space explorer!",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker/index.html"),
      coverImage: "/planet-clicker-bj.webp",
      coverAlt: "Planet Clicker Background",
      metadataDescription: "Planet Clicker is an addictive idle game where you explore planets, upgrade your space fleet, and build your galactic empire. Click your way to success and become the ultimate space explorer!",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Planet Clicker is an addictive idle game where you explore planets, upgrade your space fleet, and build your galactic empire. Click your way to success and become the ultimate space explorer!</p>\n        </section>",
    },
  },
  "planet-clicker-2": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker 2",
    image: "/planet-clicker-2-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["single-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Experience the enhanced version of Planet Clicker with improved graphics, new features, and more engaging gameplay! Explore new galaxies, upgrade your space fleet, and become the ultimate cosmic explorer in this addictive idle game.",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker-2/index.html"),
      coverImage: "/planet-clicker-2-bj.webp",
      coverAlt: "Planet Clicker 2 Background",
      metadataDescription: "Experience the enhanced version of Planet Clicker with improved graphics, new features, and more engaging gameplay! Explore new galaxies, upgrade your space fleet, and become the ultimate cosmic explorer in this addictive idle game.",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker 2</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Experience the enhanced version of Planet Clicker with improved graphics, new features, and more engaging gameplay! Explore new galaxies, upgrade your space fleet, and become the ultimate cosmic explorer in this addictive idle game.</p>\n        </section>",
    },
  },
  "planet-clicker-unlocked": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker Unlocked",
    image: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-unlocked/planet-clicker-unlocked-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["single-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Planet Clicker Unlocked is a modified version of the original Planet Clicker, allowing users to easily unlock in-game features by increasing score acquisition.",
    siteAddedAt: "2026-05-18",
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker-unlocked/index.html"),
      coverImage: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-unlocked/planet-clicker-unlocked-bj.webp",
      coverAlt: "Planet Clicker Unlocked Background",
      metadataDescription: "Planet Clicker Unlocked is a modified version of the original Planet Clicker, allowing users to easily unlock in-game features by increasing score acquisition.",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker Unlocked</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Planet Clicker Unlocked is a modified version of the original Planet Clicker, allowing users to easily unlock in-game features by increasing score acquisition.</p>\n        </section>",
    },
  },
  "planet-clicker-pro": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker Pro",
    image: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-pro/planet-clicker-pro-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["single-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Planet Clicker Pro is an expansion DLC of the original Planet Clicker, featuring additional planets beyond the original content.",
    siteAddedAt: "2026-05-18",
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker-pro/index.html"),
      coverImage: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-pro/planet-clicker-pro-bj.webp",
      coverAlt: "Planet Clicker Pro Background",
      metadataDescription: "Planet Clicker Pro is an expansion DLC of the original Planet Clicker, featuring additional planets beyond the original content.",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker Pro</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Planet Clicker Pro is an expansion DLC of the original Planet Clicker, featuring additional planets beyond the original content.</p>\n        </section>",
    },
  },
  "planet-clicker-2019": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker 2019",
    image: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-2019/planet-clicker-2019-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["single-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Planet Clicker 2019 is a pioneering version that predates the original Planet Clicker by a year. With retro graphics and classic gameplay, it ranks as the third most popular game on Scratch and represents the true beginning of the Planet Clicker series.",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker-2019/index.html"),
      coverImage: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-2019/planet-clicker-2019-bj.webp",
      coverAlt: "Planet Clicker 2019 Background",
      metadataDescription: "Planet Clicker 2019 is a pioneering version that predates the original Planet Clicker by a year. With retro graphics and classic gameplay, it ranks as the third most popular game on Scratch and represents the true beginning of the Planet Clicker series.",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker 2019</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Planet Clicker 2019 is a pioneering version that predates the original Planet Clicker by a year. With retro graphics and classic gameplay, it ranks as the third most popular game on Scratch and represents the true beginning of the Planet Clicker series.</p>\n        </section>",
    },
  },
  "planet-clicker-2022": {
    categoryId: "sci-fi-clicker-games",
    title: "Planet Clicker 2022",
    image: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-2022/planet-clicker-2022-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["multiplayer"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Planet Clicker 2022 is the second most popular Planet Clicker game on Scratch. This unique version offers a distinctly different gameplay experience with innovative mechanics and a dynamic leaderboard system that enhances player engagement.",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: gameAssetUrl("sci-fi-clicker-games/planet-clicker-2022/index.html"),
      coverImage: "https://mt.free-online-games.co/planet-clicker-game/planet-clicker-2022/planet-clicker-2022-bj.webp",
      coverAlt: "Planet Clicker 2022 Background",
      metadataDescription: "Planet Clicker 2022 is the second most popular Planet Clicker game on Scratch. This unique version offers a distinctly different gameplay experience with innovative mechanics and a dynamic leaderboard system that enhances player engagement.",
      description: "<section class=\"mb-12\">\n          <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">About Planet Clicker 2022</h3>\n          <p class=\"text-gray-700 dark:text-gray-300\">Planet Clicker 2022 is the second most popular Planet Clicker game on Scratch. This unique version offers a distinctly different gameplay experience with innovative mechanics and a dynamic leaderboard system that enhances player engagement.</p>\n        </section>",
    },
  },
  // game:add insertion point; keep this line.
} satisfies Record<string, GameDefinitionData>;
