import type { GameDefinitionData } from "@/config/game-schema";
import { gameAssetUrl } from "@/site/site";

export const GAME_DEFINITIONS = {
  "2v2-io": {
    categoryId: "2v2-io-games",
    title: "2v2.io",
    image: "/2v2-io-logo.webp",
    plays: 0,
    tags: ["PvP", "Building", "Battle Royale"],
    gameAttributes: {
      playerModes: ["two-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​",
    siteAddedAt: "2026-05-18",
    isHot: true,
    detail: {
      playUrl: "https://game.1v1-lol.cc/1v1-lol-games/2v2-io/2v2-io.html",
      coverImage: "/2v2-io-bj.webp",
      coverAlt: "2v2.io Background",
      metadataDescription: "2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​",
      description: "<section><h3>About 2v2.io</h3><p>2v2.io is a fast-paced battle royale game that fuses sharp shooting with instant building, where you and your teammate fight to be the last squad standing in a shrinking arena.​</p></section>",
    },
  },
  "1v1-lol": {
    categoryId: "2v2-io-games",
    title: "1v1.LOL",
    image: "https://mt.buildnow-gg.org/buildnow-gg-games/1v1-lol/1v1-lol-logo.webp",
    plays: 0,
    tags: ["PvP", "Building", "Battle Royale"],
    gameAttributes: {
      playerModes: ["two-player"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "1v1.LOL is the ultimate building and shooting game where you construct defensive structures and engage in intense firefights. Test your reflexes and strategic skills in this addictive battle royale adventure!",
    siteAddedAt: "2026-08-11",
    isHot: true,
    detail: {
      playUrl: "https://mt.1v1-lol.cc/1v1-lol-games/1v1-lol/3.9/index.html",
      coverImage: "https://mt.buildnow-gg.org/buildnow-gg-games/1v1-lol/1v1-lol-bj.webp",
      coverAlt: "1v1.LOL Background",
      metadataDescription: "1v1.LOL is the ultimate building and shooting game where you construct defensive structures and engage in intense firefights. Test your reflexes and strategic skills in this addictive battle royale adventure!",
      description: "<section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to 1v1.LOL!</h3>\n      <p class=\"text-gray-700 dark:text-gray-300\">1v1.LOL is the ultimate building and shooting game that combines fast-paced combat with strategic construction. Build defensive structures, engage in intense firefights, and prove your skills in this addictive battle royale adventure!</p>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n      <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>Fast-paced building and shooting gameplay</li>\n        <li>Multiple game modes including Battle Royale and Box Fight</li>\n        <li>Advanced building mechanics with walls, floors, and ramps</li>\n        <li>Weapon variety including assault rifles, shotguns, and sniper rifles</li>\n        <li>Real-time multiplayer battles</li>\n        <li>Customizable controls and settings</li>\n        <li>Regular updates with new features and improvements</li>\n      </ul>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n      <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>Use WASD keys to move your character</li>\n        <li>Left click to shoot and right click to aim</li>\n        <li>Use Q, C, V, X keys to build walls, floors, stairs, and roofs</li>\n        <li>Press R to reload your weapon</li>\n        <li>Use number keys 1-5 to switch between weapons</li>\n        <li>Build strategically to protect yourself and gain advantages</li>\n        <li>Eliminate opponents to be the last player standing</li>\n      </ol>\n    </section>\n\n    <section>\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Pro Tips</h3>\n      <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n        <p>• Master the building mechanics - they're crucial for defense and offense</p>\n        <p>• Practice your aim in the training mode before jumping into battles</p>\n        <p>• Learn to build quickly under pressure to outmaneuver opponents</p>\n        <p>• Use high ground advantage whenever possible</p>\n        <p>• Manage your resources wisely - materials are limited</p>\n        <p>• Stay aware of the storm circle and plan your movements accordingly</p>\n      </div>\n    </section>",
    },
  },
  "buildnow-gg": {
    categoryId: "2v2-io-games",
    title: "BuildNow GG",
    image: "https://mt.1v1-lol.cc/1v1-lol-games/buildnow-gg/buildnow-gg-logo.webp",
    plays: 0,
    tags: ["1v1", "Building"],
    gameAttributes: {
      playerModes: ["single-player", "multiplayer", "two-player"],
      controls: ["keyboard-mouse", "gamepad"],
      loadSpeed: "fast-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "BuildNow GG is an exciting building and battle royale game where you can construct defensive structures and engage in intense multiplayer battles. Test your building skills, reflexes, and strategic thinking in this fast-paced construction combat game!",
    rating: 4.8,
    createdAt: "2024-01-10",
    siteAddedAt: "2025-12-19",
    isHot: true,
    detail: {
      playUrl: "https://mt.1v1-lol.cc/1v1-lol-games/buildnow-gg/v0.3.2.2/index.html",
      coverImage: "https://mt.1v1-lol.cc/1v1-lol-games/buildnow-gg/buildnow-gg-bj.webp",
      coverAlt: "BuildNow GG Background",
      metadataDescription: "Play BuildNow GG, an exciting building and battle royale game where you can construct defensive structures and engage in intense multiplayer battles. Test your building skills, reflexes, and strategic thinking in this fast-paced construction combat game!",
      description: "<section class=\"mb-12\">\n            <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to BuildNow GG!</h3>\n            <p class=\"text-gray-700 dark:text-gray-300\">BuildNow GG is an exciting building and battle royale game where you can construct defensive structures and engage in intense multiplayer battles. Test your building skills, reflexes, and strategic thinking in this fast-paced construction combat game!</p>\n          </section>\n      \n          <section class=\"mb-12\">\n            <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n            <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n              <li>Advanced building mechanics with multiple structure types</li>\n              <li>Fast-paced multiplayer battles with up to 100 players</li>\n              <li>Various game modes including Solo, Duos, and Squad</li>\n              <li>Customizable controls and settings</li>\n              <li>Diverse weapon arsenal and equipment</li>\n              <li>Regular updates with new content and features</li>\n              <li>Cross-platform compatibility</li>\n            </ul>\n          </section>\n      \n          <section class=\"mb-12\">\n            <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n            <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n              <li>Use WASD or arrow keys to move your character</li>\n              <li>Press spacebar to jump and double-tap to activate boost</li>\n              <li>Use mouse to aim and left-click to shoot</li>\n              <li>Press Q, E, R, and F to select different building structures</li>\n              <li>Right-click to place selected building structure</li>\n              <li>Press 1-5 to switch between weapons</li>\n              <li>Press C to crouch and Z to prone</li>\n            </ol>\n          </section>\n      \n          <section>\n            <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Tips for Success</h3>\n            <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n              <p>• Master building techniques to gain tactical advantages</p>\n              <p>• Learn to build and edit structures quickly during combat</p>\n              <p>• Collect resources efficiently to ensure you have building materials</p>\n              <p>• Practice different building patterns for defense and offense</p>\n              <p>• Use high ground advantage whenever possible</p>\n              <p>• Combine building with strategic movement to outplay opponents</p>\n              <p>• Stay aware of the shrinking safe zone and plan accordingly</p>\n            </div>\n          </section>",
    },
  },
  "fortzone-battle-royale": {
    categoryId: "2v2-io-games",
    title: "Fortzone Battle Royale",
    image: "https://mt.buildnow-gg.org/buildnow-gg-games/fortzone-battle-royale/fortzone-battle-royale-logo.webp",
    plays: 0,
    tags: ["PvP", "Building", "Battle Royale"],
    gameAttributes: {
      playerModes: ["multiplayer"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Fortzone Battle Royale is an epic battle royale game that combines building mechanics with intense survival gameplay. Gather resources, construct fortifications, and fight to be the last player standing in this thrilling multiplayer experience!",
    siteAddedAt: "2026-07-08",
    isHot: true,
    detail: {
      playUrl: "https://game.buildnow-gg.org/buildnow-gg-games/fortzone-battle-royale/fortzone-battle-royale.html",
      coverImage: "https://mt.buildnow-gg.org/buildnow-gg-games/fortzone-battle-royale/fortzone-battle-royale-bj.webp",
      coverAlt: "Fortzone Battle Royale Background",
      metadataDescription: "Fortzone Battle Royale is an epic battle royale game that combines building mechanics with intense survival gameplay. Gather resources, construct fortifications, and fight to be the last player standing in this thrilling multiplayer experience!",
      description: "<section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to Fortzone Battle Royale!</h3>\n      <p class=\"text-gray-700 dark:text-gray-300\">Fortzone Battle Royale is an epic battle royale game that combines building mechanics with intense survival gameplay. Gather resources, construct fortifications, and fight to be the last player standing in this thrilling multiplayer experience. Master both combat and construction skills to dominate the battlefield!</p>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n      <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>Epic battle royale gameplay with building mechanics</li>\n        <li>Resource gathering and construction system</li>\n        <li>Multiple weapon types and equipment options</li>\n        <li>Dynamic shrinking battlefield</li>\n        <li>Solo and team-based game modes</li>\n        <li>Stunning graphics and smooth gameplay</li>\n      </ul>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n      <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>Drop into the battlefield and start gathering resources</li>\n        <li>Collect weapons, ammunition, and building materials</li>\n        <li>Use WASD keys to move and mouse to aim and shoot</li>\n        <li>Build walls, ramps, and structures for defense and advantage</li>\n        <li>Stay within the safe zone as the storm closes in</li>\n        <li>Eliminate opponents and be the last player or team standing</li>\n      </ol>\n    </section>\n\n    <section>\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Pro Tips</h3>\n      <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n        <p>• Balance resource gathering with combat readiness</p>\n        <p>• Master building techniques for quick defensive structures</p>\n        <p>• Always be aware of the storm's movement and timing</p>\n        <p>• Use high ground advantage whenever possible</p>\n        <p>• Practice different weapon combinations to find your preferred loadout</p>\n        <p>• Coordinate with your team in squad modes for better survival chances</p>\n      </div>\n    </section>",
    },
  },
  "mini-royale-nations": {
    categoryId: "2v2-io-games",
    title: "Mini Royale: Nations",
    image: "https://mt.buildnow-gg.org/buildnow-gg-games/mini-royale-nations/mini-royale-nations-logo.webp",
    plays: 0,
    tags: ["PvP", "Battle Royale"],
    gameAttributes: {
      playerModes: ["multiplayer"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Mini Royale: Nations is an intense battle royale game where you fight for survival in a shrinking battlefield. Choose your nation, gather weapons, and be the last one standing in this thrilling multiplayer combat experience!",
    siteAddedAt: "2026-07-08",
    isHot: true,
    detail: {
      playUrl: "https://game.buildnow-gg.org/buildnow-gg-games/mini-royale-nations/mini-royale-nations.html",
      coverImage: "https://mt.buildnow-gg.org/buildnow-gg-games/mini-royale-nations/mini-royale-nations-bj.webp",
      coverAlt: "Mini Royale: Nations Background",
      metadataDescription: "Mini Royale: Nations is an intense battle royale game where you fight for survival in a shrinking battlefield. Choose your nation, gather weapons, and be the last one standing in this thrilling multiplayer combat experience!",
      description: "<section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to Mini Royale: Nations!</h3>\n      <p class=\"text-gray-700 dark:text-gray-300\">Mini Royale: Nations is an intense battle royale game where you fight for survival in a shrinking battlefield. Choose your nation, gather powerful weapons, and use strategic tactics to be the last one standing in this thrilling multiplayer combat experience!</p>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n      <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🌍 Choose from multiple nations with unique abilities</li>\n        <li>⚔️ Intense battle royale gameplay with shrinking zones</li>\n        <li>🔫 Wide variety of weapons and equipment to collect</li>\n        <li>🏆 Competitive multiplayer matches</li>\n        <li>🎯 Strategic combat and tactical gameplay</li>\n        <li>🗺️ Dynamic battlefields and environments</li>\n        <li>👥 Team up with friends or go solo</li>\n        <li>📊 Ranking system and leaderboards</li>\n      </ul>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n      <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🎮 Use WASD keys to move your character</li>\n        <li>🖱️ Use mouse to aim and left-click to shoot</li>\n        <li>🏃 Press Shift to run and Ctrl to crouch</li>\n        <li>🎒 Press Tab to open inventory and manage items</li>\n        <li>🔄 Press R to reload your weapon</li>\n        <li>🗺️ Check the map regularly to stay within the safe zone</li>\n        <li>💊 Collect health items and armor for survival</li>\n        <li>🏆 Eliminate opponents and be the last one standing</li>\n      </ol>\n    </section>\n\n    <section>\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Pro Tips for Victory</h3>\n      <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n        <p>🎯 <strong>Master Your Aim:</strong> Practice your shooting accuracy in training mode before jumping into matches</p>\n        <p>🗺️ <strong>Zone Awareness:</strong> Always keep an eye on the shrinking zone and plan your movements accordingly</p>\n        <p>🎒 <strong>Loot Management:</strong> Prioritize essential items like weapons, ammo, and healing supplies</p>\n        <p>🏠 <strong>Use Cover:</strong> Take advantage of buildings and terrain for protection during firefights</p>\n        <p>🤫 <strong>Stay Stealthy:</strong> Sometimes avoiding fights early game can help you survive longer</p>\n        <p>🎧 <strong>Audio Cues:</strong> Listen for footsteps and gunshots to locate nearby enemies</p>\n        <p>⚡ <strong>Quick Decisions:</strong> Make fast decisions in combat situations to gain the upper hand</p>\n        <p>🤝 <strong>Team Communication:</strong> If playing in teams, communicate effectively with your squad</p>\n      </div>\n    </section>",
    },
  },
  "voxiom-io": {
    categoryId: "2v2-io-games",
    title: "Voxiom.io",
    image: "https://mt.buildnow-gg.org/buildnow-gg-games/voxiom-io/voxiom-io-logo.webp",
    plays: 0,
    tags: ["PvP", "Building", "Battle Royale"],
    gameAttributes: {
      playerModes: ["multiplayer"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp", "building", "battle-royale"],
      perspective: ["third-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Voxiom.io is an exciting voxel-based battle royale game that combines building mechanics with intense combat. Gather resources, construct defenses, and fight to be the last player standing in this unique 3D multiplayer experience!",
    siteAddedAt: "2026-07-08",
    isHot: true,
    detail: {
      playUrl: "https://game.buildnow-gg.org/buildnow-gg-games/voxiom-io/voxiom-io.html",
      coverImage: "https://mt.buildnow-gg.org/buildnow-gg-games/voxiom-io/voxiom-io-bj.webp",
      coverAlt: "Voxiom.io Background",
      metadataDescription: "Voxiom.io is an exciting voxel-based battle royale game that combines building mechanics with intense combat. Gather resources, construct defenses, and fight to be the last player standing in this unique 3D multiplayer experience!",
      description: "<section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to Voxiom.io!</h3>\n      <p class=\"text-gray-700 dark:text-gray-300\">Voxiom.io is an exciting voxel-based battle royale game that combines building mechanics with intense combat. In this unique 3D multiplayer experience, you'll gather resources, construct defensive structures, and fight to be the last player standing. The game features stunning voxel graphics and innovative gameplay that blends creativity with competitive action!</p>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n      <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🧱 Unique voxel-based graphics and environments</li>\n        <li>⚔️ Intense battle royale gameplay with building mechanics</li>\n        <li>🔨 Gather resources and construct defensive structures</li>\n        <li>🌍 Large 3D maps with destructible environments</li>\n        <li>🔫 Wide variety of weapons and equipment</li>\n        <li>👥 Multiplayer battles with up to 100 players</li>\n        <li>🏆 Competitive ranking system</li>\n        <li>🎮 Smooth controls and responsive gameplay</li>\n      </ul>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n      <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🎮 Use WASD keys to move your character</li>\n        <li>🖱️ Use mouse to look around and left-click to shoot</li>\n        <li>🏃 Hold Shift to run faster</li>\n        <li>🦆 Press Ctrl to crouch for stealth</li>\n        <li>🔨 Left-click to mine blocks and gather resources</li>\n        <li>🧱 Right-click to place blocks and build structures</li>\n        <li>🔄 Press R to reload your weapon</li>\n        <li>🎒 Press Tab to open inventory and manage items</li>\n        <li>🗺️ Stay within the safe zone to avoid taking damage</li>\n        <li>🏆 Eliminate other players and be the last one standing</li>\n      </ol>\n    </section>\n\n    <section>\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Pro Tips for Victory</h3>\n      <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n        <p>🏗️ <strong>Master Building:</strong> Learn to quickly construct walls and ramps for protection during firefights</p>\n        <p>⛏️ <strong>Resource Management:</strong> Efficiently gather materials early game to ensure you have enough for late-game battles</p>\n        <p>🎯 <strong>High Ground Advantage:</strong> Always try to build higher than your opponents for better positioning</p>\n        <p>🗺️ <strong>Zone Awareness:</strong> Keep track of the shrinking safe zone and plan your movements accordingly</p>\n        <p>🔫 <strong>Weapon Priority:</strong> Focus on finding better weapons and sufficient ammunition</p>\n        <p>🏠 <strong>Smart Building:</strong> Don't over-build - conserve materials for crucial moments</p>\n        <p>👂 <strong>Audio Cues:</strong> Listen for footsteps, building sounds, and gunshots to locate enemies</p>\n        <p>⚡ <strong>Quick Edits:</strong> Practice editing your structures quickly to create windows and escape routes</p>\n        <p>🤝 <strong>Team Strategy:</strong> In team modes, coordinate building and share resources with teammates</p>\n        <p>🎨 <strong>Creative Defense:</strong> Use the environment and your building skills to create unique defensive positions</p>\n      </div>\n    </section>",
    },
  },
  "krunker-io": {
    categoryId: "2v2-io-games",
    title: "Krunker.io",
    image: "https://mt.buildnow-gg.org/buildnow-gg-games/krunker-io/krunker-io-logo.webp",
    plays: 0,
    tags: ["PvP"],
    gameAttributes: {
      playerModes: ["multiplayer"],
      controls: ["keyboard-mouse"],
      loadSpeed: "normal-loading",
      gameplay: ["pvp"],
      perspective: ["first-person"],
    },
    developer: "Independent Studio",
    technology: "HTML5",
    platforms: ["Web Browser"],
    description: "Krunker.io is a fast-paced multiplayer FPS game featuring pixelated graphics and intense combat. Choose from various classes, customize your weapons, and dominate the battlefield in this addictive browser-based shooter!",
    siteAddedAt: "2026-07-08",
    isHot: true,
    detail: {
      playUrl: "https://game.buildnow-gg.org/buildnow-gg-games/krunker-io/krunker-io.html",
      coverImage: "https://mt.buildnow-gg.org/buildnow-gg-games/krunker-io/krunker-io-bj.webp",
      coverAlt: "Krunker.io Background",
      metadataDescription: "Krunker.io is a fast-paced multiplayer FPS game featuring pixelated graphics and intense combat. Choose from various classes, customize your weapons, and dominate the battlefield in this addictive browser-based shooter!",
      description: "<section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Welcome to Krunker.io!</h3>\n      <p class=\"text-gray-700 dark:text-gray-300\">Krunker.io is a fast-paced multiplayer FPS game that brings intense combat action to your browser. With its unique pixelated graphics and smooth gameplay, you'll experience thrilling battles across various game modes. Choose from different classes, customize your weapons, and prove your skills in this addictive online shooter!</p>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Game Features</h3>\n      <ul class=\"list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🎯 Fast-paced multiplayer FPS gameplay</li>\n        <li>🎨 Unique pixelated graphics and smooth animations</li>\n        <li>⚔️ Multiple character classes with different abilities</li>\n        <li>🔫 Extensive weapon customization system</li>\n        <li>🏆 Various game modes including Team Deathmatch and Free-for-All</li>\n        <li>🗺️ Multiple maps with different layouts and strategies</li>\n        <li>🎮 Browser-based gameplay - no downloads required</li>\n        <li>📊 Ranking system and leaderboards</li>\n      </ul>\n    </section>\n\n    <section class=\"mb-12\">\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">How to Play</h3>\n      <ol class=\"list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300\">\n        <li>🎮 Use WASD keys to move your character</li>\n        <li>🖱️ Use mouse to aim and left-click to shoot</li>\n        <li>🏃 Hold Shift to run faster</li>\n        <li>🦆 Press Ctrl to crouch for better accuracy</li>\n        <li>🔄 Press R to reload your weapon</li>\n        <li>🎯 Right-click to aim down sights for precision</li>\n        <li>🔢 Use number keys to switch between weapons</li>\n        <li>🏆 Eliminate enemies to earn points and climb the leaderboard</li>\n      </ol>\n    </section>\n\n    <section>\n      <h3 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-4\">Pro Tips for Domination</h3>\n      <div class=\"space-y-4 text-gray-700 dark:text-gray-300\">\n        <p>🎯 <strong>Master Your Aim:</strong> Practice your crosshair placement and learn to pre-aim common angles</p>\n        <p>🏃 <strong>Movement is Key:</strong> Use slide-hopping and bunny-hopping techniques to move faster and avoid enemy fire</p>\n        <p>🔫 <strong>Know Your Weapons:</strong> Each weapon has different damage, range, and recoil patterns - learn them all</p>\n        <p>🗺️ <strong>Map Knowledge:</strong> Learn the layout of each map, including common camping spots and flanking routes</p>\n        <p>⚡ <strong>Quick Reactions:</strong> Develop fast reflexes for those crucial split-second encounters</p>\n        <p>🎨 <strong>Customize Wisely:</strong> Choose weapon skins and attachments that suit your playstyle</p>\n        <p>👥 <strong>Team Play:</strong> In team modes, coordinate with teammates and watch each other's backs</p>\n        <p>📊 <strong>Learn from Deaths:</strong> Analyze your deaths to understand what went wrong and improve</p>\n      </div>\n    </section>",
    },
  },
  // game:add insertion point; keep this line.
} satisfies Record<string, GameDefinitionData>;
